spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/codinghermit
    username: postgres
    password: 1997
    driver-class-name: org.postgresql.Driver
  security:
    user:
      password: 123
  # Cache
  redis:
    host: localhost
    port: 6379
  # cache:
  #   type: redis
  #   redis:
  #     time-to-live: 6000

server:
  port: 4000

# Env
# caching:
#   spring:
#     userListTTL: 6000
