spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/codinghermit
    username: postgres
    password: 1997
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: 123
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
            user-name-attribute: user1
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
  # Cache
  redis:
    host: localhost
    port: 6379
  # cache:
  #   type: redis
  #   redis:
  #     time-to-live: 6000

server:
  port: 4000

# Env
# caching:
#   spring:
#     userListTTL: 6000
